In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a1.dtype, a1.shape, a1.size

(dtype('int64'), (3,), 3)

In [4]:
a2=np.array([[1,2,3],
             [4,5,6]])
a2.dtype,a2.shape,a2.size

(dtype('int64'), (2, 3), 6)

In [7]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],

             [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [8]:
a3.size,a3.shape,a3.dtype

(18, (2, 3, 3), dtype('int64'))

In [9]:
a3.ndim,a2.ndim,a1.ndim

(3, 2, 1)

In [11]:
import pandas as pd

In [16]:
dataF=pd.DataFrame(a2)
dataF

0  1  2
0  1  2  3
1  4  5  6

In [18]:
# zeros and ones 
ones=np.ones(shape=(3,3))
zeros=np.zeros(shape=(3,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# using arange function
arange_array=np.arange(1,12,2)
arange_array

array([ 1,  3,  5,  7,  9, 11])

In [26]:
random_array=np.random.randint(0,10,size=(3,3))  # takes lowest highest and size
random_array

array([[6, 5, 9],
       [4, 9, 7],
       [5, 2, 8]], dtype=int32)

In [28]:
random_array_2=np.random.random((3,2))
random_array_2

array([[0.75839303, 0.43181273],
       [0.73119577, 0.78130671],
       [0.15312929, 0.2454358 ]])

In [31]:
random_aray_3=np.random.rand(3,3)
random_aray_3

array([[0.49512198, 0.76064649, 0.45458176],
       [0.52849602, 0.43432236, 0.56873969],
       [0.96546502, 0.47510068, 0.88423659]])

# viewing arrays 

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a4=np.random.randint(10,size=(5,3))
a4

array([[3, 2, 0],
       [6, 3, 1],
       [3, 4, 1],
       [9, 7, 8],
       [9, 1, 7]], dtype=int32)

In [43]:
a4[:,:3]

array([[3, 2, 0],
       [6, 3, 1],
       [3, 4, 1],
       [9, 7, 8],
       [9, 1, 7]], dtype=int32)

In [44]:
a4[:,:2]

array([[3, 2],
       [6, 3],
       [3, 4],
       [9, 7],
       [9, 1]], dtype=int32)

In [45]:
a4[:,:1]

array([[3],
       [6],
       [3],
       [9],
       [9]], dtype=int32)

# Manipulating Arrays and comparing 

In [46]:
a1

array([1, 2, 3])

In [47]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [49]:
a1+zeros

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [50]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [52]:
a1*ones   # Element wise 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [53]:
a1/ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [54]:
a1//ones # floor division

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])