In [1]:
# Make imports 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
# Load the Data 
heart_disease=pd.read_csv("data/heart_disease.csv")
heart_disease.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   60    1   3     145   233    1        0       150     0      2.3    0   
1   35    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   55    1   1     120   236    0        1       178     0      0.8    2   
4   56    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [3]:
# split data into features and labels
X=heart_disease.drop("output",axis=1)
y=heart_disease["output"]
X.shape,y.shape

((289, 13), (289,))

In [4]:
heart_disease.isna().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

# `In This Section we will`
* Clean Data
* Transform Data
* Reduce Data (To reduce1 overall cost if less data brings us same results)

In [5]:
car_sales=pd.read_csv("data/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [6]:
# Feature and label split done 
X=car_sales.drop("Price",axis=1)
y=car_sales["Price"]

In [7]:
# Three splits made 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [8]:
# Lets Try to make a model out of this data
# from sklearn.ensemble import RandomForestRegressor
# model=RandomForestRegressor()
# model.fit(X_train,y_train)
# model.score(X_test,y_test)

`The error above means ML Models can't work with categorical data like string to fix this lets convert our data to > Numerical Data `

In [9]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']

one_hot = OneHotEncoder()

transformer = ColumnTransformer(
    transformers=[
        ('one_hot', one_hot, categorical_features)
    ],
    remainder='passthrough'
)

transformed_X = transformer.fit_transform(X)
pd.DataFrame(transformed_X)


0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [11]:
X_train,X_test,y_train,y_test=train_test_split(transformed_X,y,test_size=0.2)

# The other way to do the same is 

In [12]:
dummies=pd.get_dummies(car_sales[["Make","Colour"]])
dummies

Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0       False        True        False        False         False   
1        True       False        False        False         False   
2       False        True        False        False         False   
3       False       False        False         True         False   
4       False       False         True        False         False   
..        ...         ...          ...          ...           ...   
995     False       False        False         True          True   
996     False       False         True        False         False   
997     False       False         True        False         False   
998     False        True        False        False         False   
999     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 9 columns]

In [13]:
transformed_X.shape,y_train.shape

((1000, 13), (800,))

In [14]:
# Refit the model 
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.2738741687923545

`Now lets handle Missing Data`

To handle Missing data way have two ways:
* Imputation (Filling missing values with some value)
* Removing the values 

In [15]:
car_sales_missing=pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [16]:
# Find Missing values
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

The Dataset above has a lot of missing data values so lets fix it now

In [17]:
car_sales_missing['Make'].fillna("missing",inplace=True)
car_sales_missing.isna().sum()

C:\Users\fairo\AppData\Local\Temp\ipykernel_1480\2415722170.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing['Make'].fillna("missing",inplace=True)


Make              0
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [18]:
import warnings
warnings.filterwarnings("ignore")

In [19]:
car_sales_missing["Colour"].fillna("missing",inplace=True)
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [20]:
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(),inplace=True)
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors            50
Price            50
dtype: int64

In [21]:
np.round(car_sales_missing["Doors"].mean())

np.float64(4.0)

In [22]:
car_sales_missing["Doors"].fillna(4,inplace=True)
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [23]:
# Drop those rows which have missing labels
car_sales_missing.dropna(inplace=True)

In [24]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [25]:
car_sales_missing.head(2)

Make Colour  Odometer (KM)  Doors    Price
0  Honda  White        35431.0    4.0  15323.0
1    BMW   Blue       192714.0    5.0  19943.0

In [26]:
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

Convert string or `object data` in features to the `Numerical data`

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer(
    transformers=[
        ("one_hot",one_hot,categorical_features)
    ],
    remainder="passthrough")
transformed_X=transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 4.00000e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.92714e+05, 5.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 4.00000e+00],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 4.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 4.00000e+00]], shape=(950, 13))

In [28]:
X_train,X_test,y_train,y_test=train_test_split(transformed_X,y,test_size=0.2)

In [29]:
model.fit(X_train,y_train)

RandomForestRegressor()

In [30]:
model.score(X_test,y_test)

0.2649007128697696

# Filling Missing Values with Scikit-learn now

In [31]:
car_sales_missing=pd.read_csv("data/car-sales-extended-missing-data.csv")
len(car_sales_missing)

1000

In [32]:
# First drop all those rows which have no labels
car_sales_missing.dropna(subset=["Price"],inplace=True)
len(car_sales_missing)

950

car_sales_missing.isna().sum()

In [33]:
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [34]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [35]:
# Creating Imputers 
cat_imputer=SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy="mean")
# Define data
cat_featuers=["Make","Colour"]
door_features=['Doors']
num_features=["Odometer (KM)"]
# Define Pipeline 
imputer= ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_featuers),
    ("door_imputer",door_imputer,door_features),
    ("num_imputer",num_imputer,num_features)
])
filled_X_train=imputer.fit_transform(X_train)
filled_X_test=imputer.transform(X_test)

In [36]:
type(filled_X_train)

numpy.ndarray

In [37]:
filled_X_train

array([['Toyota', 'Blue', 4.0, 237448.0],
       ['Nissan', 'White', 4.0, 131910.7281553398],
       ['Honda', 'Black', 4.0, 147889.0],
       ...,
       ['Toyota', 'Blue', 4.0, 169449.0],
       ['Honda', 'White', 4.0, 215235.0],
       ['missing', 'White', 4.0, 126669.0]], shape=(760, 4), dtype=object)

In [38]:
# Get our Transformed Data back into DatFrame
car_sales_filled_train=pd.DataFrame(filled_X_train,columns=["Make","Colour","Doors","Odometer (KM)"])
car_sales_filled_test=pd.DataFrame(filled_X_test,columns=["Make","Colour","Doors","Odometer (KM)"])
type(car_sales_filled_test),type(car_sales_filled_train)

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

In [39]:
# check data types now 
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [40]:
car_sales_filled_train.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [41]:
car_sales_filled_test.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [42]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer(
    transformers=[
        ("one_hot",one_hot,categorical_features)
    ],
    remainder="passthrough")
transformed_X_train=transformer.fit_transform(car_sales_filled_train)
transformed_X_test=transformer.transform(car_sales_filled_test)


In [43]:
# Model Creation 
np.random.seed(42)

from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

model.fit(transformed_X_train,y_train)
model.score(transformed_X_test,y_test)

0.2510916227949118

Whenever you need to Choose a model goto map provided by Sklearn https://scikit-learn.org/stable/machine_learning_map.html

In [47]:
# Lets work with house pricing 
boston=pd.read_csv("https://raw.githubusercontent.com/FairozAhmadSheikh/Datasets_CSV/refs/heads/main/Boston.csv")
boston.head()

CRIM    ZN  INDUS  CHAS     NX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [48]:
boston_df=boston.rename(columns={"MEDV":"target"})
boston_df.head(2)

CRIM    ZN  INDUS  CHAS     NX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   

   PTRATIO      B  LSTAT  target  
0     15.3  396.9   4.98    24.0  
1     17.8  396.9   9.14    21.6

In [49]:
len(boston_df)

506

In [51]:
# go to sklearn documentation and choose a model that fits according to problem 
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
# Split in features and target 
X=boston_df.drop("target",axis=1)
y=boston_df["target"]
# Train test split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Model 
model=Ridge()

# Train model 
model.fit(X_train,y_train)

model.score(X_test,y_test)

0.7991878315708332

Above Model has accuracy near to 80% lets see if we can improve by selecting another model 

In [52]:
from sklearn.ensemble import RandomForestRegressor 
X=boston_df.drop("target",axis=1)
y=boston_df["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

rf=RandomForestRegressor()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.8290656308022537

Moving up a bit so keep experimenting 

### Choosing Estimator for Classification now 

In [58]:
# Heart Disease dataset
heart_disease=pd.read_csv("data/heart_disease.csv").rename(columns={"output":"target"})
heart_disease.head(2)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   60    1   3     145   233    1        0       150     0      2.3    0   
1   35    1   2     130   250    0        1       187     0      3.5    0   

   caa  thall  target  
0    0      1       1  
1    0      2       1

In [64]:
len(heart_disease)

289

In [68]:
from sklearn.svm import LinearSVC

X=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
clf=LinearSVC()

clf.fit(X_train,y_train)
clf.score(X_test,y_test)


0.8103448275862069

In [87]:
from sklearn.ensemble import RandomForestClassifier

X=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

clf=RandomForestClassifier()

clf.fit(X_train,y_train)
clf.score(X_test,y_test)



0.8793103448275862

In [91]:
# Two ways of prediction `predict` and `predict_proba` 
y_preds=clf.predict(X_test)
y_preds
y_preds_2=clf.predict_proba(X_test)
y_preds_2[:3]  # Gives probaility of classes i.e % how confident it is 

array([[0.32, 0.68],
       [0.52, 0.48],
       [0.31, 0.69]])

Same can be done  to solve `regresion problems`

In [92]:
from sklearn.ensemble import RandomForestRegressor
X=boston_df.drop("target",axis=1)
y=boston_df["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8628408295499701

In [94]:
y_preds=model.predict(X_test)
y_preds[:10]

array([27.639, 16.574, 18.713, 18.342, 25.141, 30.328, 23.507, 19.092,
       26.878, 19.135])

In [96]:
np.array(y_test[:10])

array([28.4, 14.3, 16.8, 21.5, 25. , 32.5, 16.5, 17.8, 23.9, 16. ])

In [97]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_preds,y_test)

2.428686274509803

# Lets Evaluate models using some metrics 